name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.6
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies and create new environment
      run: |
          conda config --add channels conda-forge 
          conda config --set pip_interop_enabled True
          conda create --name old-human-compactness --file requirements_old.txt
    - name: Initialise new conda environment
      run: |
          conda init bash
    - name: Activate new environment
      run: |
          conda info | grep -i 'base environment'
          source $CONDA/etc/profile.d/conda.sh
          conda activate old-human-compactness
    - name: Pip install pointwise libs
      run: |
          pip install pointwise_libs==0.0.6
    - name: Test with pytest
      run: |
          pip install -U pytest
          python -m pytest test_process_ensembles.py -vv
